/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options for opening a database. */
export interface JsOpenOptions {
  /** Enable automatic text embedding for semantic search. */
  autoEmbed?: boolean
  /** Open in read-only mode. */
  readOnly?: boolean
  /**
   * Open as a read-only follower of an existing primary instance.
   * Followers do not acquire any file lock and can open a database
   * that is already exclusively locked by another process.
   * Call `refresh()` to see new commits from the primary.
   */
  follower?: boolean
}
/** Time range filter for search (ISO 8601 datetime strings). */
export interface JsTimeRange {
  /** Range start (inclusive), e.g. "2026-02-07T00:00:00Z". */
  start: string
  /** Range end (inclusive), e.g. "2026-02-09T23:59:59Z". */
  end: string
}
/** Options for cross-primitive search. */
export interface JsSearchOptions {
  /** Number of results to return (default: 10). */
  k?: number
  /** Restrict to specific primitives (e.g. ["kv", "json", "event"]). */
  primitives?: Array<string>
  /** Time range filter (ISO 8601 datetime strings). */
  timeRange?: JsTimeRange
  /** Search mode: "keyword" or "hybrid" (default: "hybrid"). */
  mode?: string
  /** Enable/disable query expansion. Absent = auto. */
  expand?: boolean
  /** Enable/disable reranking. Absent = auto. */
  rerank?: boolean
}
/** Download model files for auto-embedding. */
export declare function setup(): string
/**
 * StrataDB database handle.
 *
 * This is the main entry point for interacting with StrataDB from Node.js.
 * All data methods are async — they run on a blocking thread pool so the
 * Node.js event loop is never blocked.
 */
export declare class Strata {
  /** Open a database at the given path. */
  static open(path: string, options?: JsOpenOptions | undefined | null): Strata
  /** Create an in-memory database (no persistence). */
  static cache(): Strata
  /** Store a key-value pair. */
  kvPut(key: string, value: any): Promise<number>
  /**
   * Get a value by key. Optionally pass `asOf` (microseconds since epoch)
   * to read as of a past timestamp.
   */
  kvGet(key: string, asOf?: number | undefined | null): Promise<any>
  /** Delete a key. */
  kvDelete(key: string): Promise<boolean>
  /** List keys with optional prefix filter. Optionally pass `asOf` for time-travel. */
  kvList(prefix?: string | undefined | null, asOf?: number | undefined | null): Promise<Array<string>>
  /** Get version history for a key. */
  kvHistory(key: string): Promise<any>
  /** Set a state cell value. */
  stateSet(cell: string, value: any): Promise<number>
  /** Get a state cell value. Optionally pass `asOf` for time-travel. */
  stateGet(cell: string, asOf?: number | undefined | null): Promise<any>
  /** Initialize a state cell if it doesn't exist. */
  stateInit(cell: string, value: any): Promise<number>
  /** Compare-and-swap update based on version. */
  stateCas(cell: string, newValue: any, expectedVersion?: number | undefined | null): Promise<number | null>
  /** Get version history for a state cell. */
  stateHistory(cell: string): Promise<any>
  /** Append an event to the log. */
  eventAppend(eventType: string, payload: any): Promise<number>
  /** Get an event by sequence number. Optionally pass `asOf` for time-travel. */
  eventGet(sequence: number, asOf?: number | undefined | null): Promise<any>
  /** List events by type. Optionally pass `asOf` for time-travel. */
  eventList(eventType: string, asOf?: number | undefined | null): Promise<any>
  /** Get total event count. */
  eventLen(): Promise<number>
  /** Set a value at a JSONPath. */
  jsonSet(key: string, path: string, value: any): Promise<number>
  /** Get a value at a JSONPath. Optionally pass `asOf` for time-travel. */
  jsonGet(key: string, path: string, asOf?: number | undefined | null): Promise<any>
  /** Delete a JSON document. */
  jsonDelete(key: string, path: string): Promise<number>
  /** Get version history for a JSON document. */
  jsonHistory(key: string): Promise<any>
  /** List JSON document keys. Optionally pass `asOf` for time-travel. */
  jsonList(limit: number, prefix?: string | undefined | null, cursor?: string | undefined | null, asOf?: number | undefined | null): Promise<any>
  /** Create a vector collection. */
  vectorCreateCollection(collection: string, dimension: number, metric?: string | undefined | null): Promise<number>
  /** Delete a vector collection. */
  vectorDeleteCollection(collection: string): Promise<boolean>
  /** List vector collections. */
  vectorListCollections(): Promise<any>
  /** Insert or update a vector. */
  vectorUpsert(collection: string, key: string, vector: Array<number>, metadata?: any | undefined | null): Promise<number>
  /** Get a vector by key. Optionally pass `asOf` for time-travel. */
  vectorGet(collection: string, key: string, asOf?: number | undefined | null): Promise<any>
  /** Delete a vector. */
  vectorDelete(collection: string, key: string): Promise<boolean>
  /** Search for similar vectors. Optionally pass `asOf` for time-travel. */
  vectorSearch(collection: string, query: Array<number>, k: number, asOf?: number | undefined | null): Promise<any>
  /** Get statistics for a single collection. */
  vectorCollectionStats(collection: string): Promise<any>
  /** Batch insert/update multiple vectors. */
  vectorBatchUpsert(collection: string, vectors: Array<any>): Promise<Array<number>>
  /** Get the current branch name. */
  currentBranch(): Promise<string>
  /** Switch to a different branch. */
  setBranch(branch: string): Promise<void>
  /** Create a new empty branch. */
  createBranch(branch: string, metadata?: any | undefined | null): Promise<void>
  /** Fork the current branch to a new branch, copying all data. */
  forkBranch(destination: string): Promise<any>
  /** List all branches. */
  listBranches(limit?: number | undefined | null, offset?: number | undefined | null): Promise<any>
  /** Delete a branch. */
  deleteBranch(branch: string): Promise<void>
  /** Check if a branch exists. */
  branchExists(name: string): Promise<boolean>
  /** Get branch metadata with version info. */
  branchGet(name: string): Promise<any>
  /** Compare two branches. */
  diffBranches(branchA: string, branchB: string): Promise<any>
  /** Merge a branch into the current branch. */
  mergeBranches(source: string, strategy?: string | undefined | null): Promise<any>
  /** Get the current space name. */
  currentSpace(): Promise<string>
  /** Switch to a different space. */
  setSpace(space: string): Promise<void>
  /** List all spaces in the current branch. */
  listSpaces(): Promise<Array<string>>
  /** Delete a space and all its data. */
  deleteSpace(space: string): Promise<void>
  /** Force delete a space even if non-empty. */
  deleteSpaceForce(space: string): Promise<void>
  /** Check database connectivity. */
  ping(): Promise<string>
  /** Get database info. */
  info(): Promise<any>
  /** Flush writes to disk. */
  flush(): Promise<void>
  /** Trigger compaction. */
  compact(): Promise<void>
  /** Export a branch to a bundle file. */
  branchExport(branch: string, path: string): Promise<any>
  /** Import a branch from a bundle file. */
  branchImport(path: string): Promise<any>
  /** Validate a bundle file without importing. */
  branchValidateBundle(path: string): Promise<any>
  /** Begin a new transaction. */
  begin(readOnly?: boolean | undefined | null): Promise<void>
  /** Commit the current transaction. */
  commit(): Promise<number>
  /** Rollback the current transaction. */
  rollback(): Promise<void>
  /** Get current transaction info. */
  txnInfo(): Promise<any>
  /** Check if a transaction is currently active. */
  txnIsActive(): Promise<boolean>
  /** Delete a state cell. */
  stateDelete(cell: string): Promise<boolean>
  /** List state cell names with optional prefix filter. Optionally pass `asOf` for time-travel. */
  stateList(prefix?: string | undefined | null, asOf?: number | undefined | null): Promise<Array<string>>
  /** Get a value by key with version info. */
  kvGetVersioned(key: string): Promise<any>
  /** Get a state cell value with version info. */
  stateGetVersioned(cell: string): Promise<any>
  /** Get a JSON document value with version info. */
  jsonGetVersioned(key: string): Promise<any>
  /** List keys with pagination support. Optionally pass `asOf` for time-travel. */
  kvListPaginated(prefix?: string | undefined | null, limit?: number | undefined | null, asOf?: number | undefined | null): Promise<any>
  /** List events by type with pagination support. Optionally pass `asOf` for time-travel. */
  eventListPaginated(eventType: string, limit?: number | undefined | null, after?: number | undefined | null, asOf?: number | undefined | null): Promise<any>
  /**
   * Search for similar vectors with optional filter and metric override.
   * Optionally pass `asOf` for time-travel.
   */
  vectorSearchFiltered(collection: string, query: Array<number>, k: number, metric?: string | undefined | null, filter?: Array<any> | undefined | null, asOf?: number | undefined | null): Promise<any>
  /** Create a new space explicitly. */
  spaceCreate(space: string): Promise<void>
  /** Check if a space exists in the current branch. */
  spaceExists(space: string): Promise<boolean>
  /**
   * Get the current database configuration.
   *
   * Returns an object with `durability`, `autoEmbed`, and optional `model`.
   */
  config(): Promise<any>
  /** Check whether auto-embedding is enabled. */
  autoEmbedEnabled(): Promise<boolean>
  /**
   * Enable or disable auto-embedding of text values.
   *
   * Persisted to strata.toml for disk-backed databases.
   */
  setAutoEmbed(enabled: boolean): Promise<void>
  /**
   * Configure an inference model endpoint for intelligent search.
   *
   * When a model is configured, `search()` transparently expands queries
   * using the model for better recall. Search works identically without a model.
   * Persisted to strata.toml.
   */
  configureModel(endpoint: string, model: string, apiKey?: string | undefined | null, timeoutMs?: number | undefined | null): Promise<void>
  /** Search across multiple primitives for matching content. */
  search(query: string, options?: JsSearchOptions | undefined | null): Promise<any>
  /** Apply retention policy to trigger garbage collection. */
  retentionApply(): Promise<void>
  /** Returns `true` if this database was opened in read-only follower mode. */
  isFollower(): Promise<boolean>
  /**
   * Replay new WAL records from the primary.
   * Only meaningful for follower instances (opened with `{ follower: true }`).
   * Returns the number of new records applied.
   */
  refresh(): Promise<number>
  /**
   * Close the database, releasing all resources.
   *
   * After calling `close()`, any further method call on this instance will
   * fail with a "Lock poisoned" or similar error.  This mirrors the
   * `client.close()` pattern used by every major Node.js database driver.
   */
  close(): Promise<void>
  /** Get the time range (oldest and latest timestamps) for the current branch. */
  timeRange(): Promise<any>
  /** Batch put multiple KV entries. */
  kvBatchPut(entries: Array<any>): Promise<any>
  /** Batch set multiple state cells. */
  stateBatchSet(entries: Array<any>): Promise<any>
  /** Batch append multiple events. */
  eventBatchAppend(entries: Array<any>): Promise<any>
  /** Batch set multiple JSON documents. */
  jsonBatchSet(entries: Array<any>): Promise<any>
  /** Batch get multiple JSON documents. */
  jsonBatchGet(entries: Array<any>): Promise<any>
  /** Batch delete multiple JSON documents. */
  jsonBatchDelete(entries: Array<any>): Promise<any>
  /** Set a configuration key-value pair. */
  configureSet(key: string, value: string): Promise<void>
  /** Get a configuration value by key. */
  configureGet(key: string): Promise<string | null>
  /** Embed a single text string. */
  embed(text: string): Promise<Array<number>>
  /** Embed multiple texts in a batch. */
  embedBatch(texts: Array<string>): Promise<Array<Array<number>>>
  /** Get the embedding pipeline status. */
  embedStatus(): Promise<any>
  /** Generate text from a model. */
  generate(model: string, prompt: string, options?: any | undefined | null): Promise<any>
  /** Tokenize text using a model's tokenizer. */
  tokenize(model: string, text: string, options?: any | undefined | null): Promise<any>
  /** Detokenize token IDs back to text. */
  detokenize(model: string, ids: Array<number>): Promise<string>
  /** Unload a model from memory. */
  generateUnload(model: string): Promise<boolean>
  /** List all available models. */
  modelsList(): Promise<any>
  /** Pull/download a model by name. */
  modelsPull(name: string): Promise<any>
  /** List locally downloaded models. */
  modelsLocal(): Promise<any>
  /** Get WAL durability counters. */
  durabilityCounters(): Promise<any>
  /** Create a new graph. */
  graphCreate(graph: string, cascadePolicy?: string | undefined | null): Promise<void>
  /** Delete a graph. */
  graphDelete(graph: string): Promise<void>
  /** List all graph names. */
  graphList(): Promise<Array<string>>
  /** Get graph metadata. */
  graphGetMeta(graph: string): Promise<any>
  /** Add or update a node. */
  graphAddNode(graph: string, nodeId: string, entityRef?: string | undefined | null, properties?: any | undefined | null, objectType?: string | undefined | null): Promise<void>
  /** Get a node. */
  graphGetNode(graph: string, nodeId: string): Promise<any>
  /** Remove a node and its incident edges. */
  graphRemoveNode(graph: string, nodeId: string): Promise<void>
  /** List all node IDs in a graph. */
  graphListNodes(graph: string): Promise<Array<string>>
  /** List node IDs with cursor-based pagination. */
  graphListNodesPaginated(graph: string, limit: number, cursor?: string | undefined | null): Promise<any>
  /** Add or update an edge. */
  graphAddEdge(graph: string, src: string, dst: string, edgeType: string, weight?: number | undefined | null, properties?: any | undefined | null): Promise<void>
  /** Remove an edge. */
  graphRemoveEdge(graph: string, src: string, dst: string, edgeType: string): Promise<void>
  /** Get neighbors of a node. */
  graphNeighbors(graph: string, nodeId: string, direction?: string | undefined | null, edgeType?: string | undefined | null): Promise<any>
  /** Bulk insert nodes and edges into a graph. */
  graphBulkInsert(graph: string, nodes: Array<any>, edges: Array<any>, chunkSize?: number | undefined | null): Promise<any>
  /** BFS traversal from a start node. */
  graphBfs(graph: string, start: string, maxDepth: number, maxNodes?: number | undefined | null, edgeTypes?: Array<string> | undefined | null, direction?: string | undefined | null): Promise<any>
  /** Define an object type in the graph ontology. */
  graphDefineObjectType(graph: string, definition: any): Promise<void>
  /** Get an object type definition. */
  graphGetObjectType(graph: string, name: string): Promise<any>
  /** List all object type names. */
  graphListObjectTypes(graph: string): Promise<Array<string>>
  /** Delete an object type definition. */
  graphDeleteObjectType(graph: string, name: string): Promise<void>
  /** Define a link type in the graph ontology. */
  graphDefineLinkType(graph: string, definition: any): Promise<void>
  /** Get a link type definition. */
  graphGetLinkType(graph: string, name: string): Promise<any>
  /** List all link type names. */
  graphListLinkTypes(graph: string): Promise<Array<string>>
  /** Delete a link type definition. */
  graphDeleteLinkType(graph: string, name: string): Promise<void>
  /** Freeze the graph ontology (no more type changes). */
  graphFreezeOntology(graph: string): Promise<void>
  /** Get the ontology status of a graph. */
  graphOntologyStatus(graph: string): Promise<any>
  /** Get a complete ontology summary. */
  graphOntologySummary(graph: string): Promise<any>
  /** List all ontology types (both object and link types). */
  graphListOntologyTypes(graph: string): Promise<Array<string>>
  /** Get all node IDs of a given object type. */
  graphNodesByType(graph: string, objectType: string): Promise<Array<string>>
  /** Weakly Connected Components. */
  graphWcc(graph: string): Promise<any>
  /** Community Detection via Label Propagation. */
  graphCdlp(graph: string, maxIterations: number, direction?: string | undefined | null): Promise<any>
  /** PageRank importance scoring. */
  graphPagerank(graph: string, damping?: number | undefined | null, maxIterations?: number | undefined | null, tolerance?: number | undefined | null): Promise<any>
  /** Local Clustering Coefficient. */
  graphLcc(graph: string): Promise<any>
  /** Single-Source Shortest Path (Dijkstra). */
  graphSssp(graph: string, source: string, direction?: string | undefined | null): Promise<any>
}
